// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1VReTwxqNSHTz2JoirdcCuVDQJgFZY28',
    appId: '1:291258072776:web:e369984f75dda14e3c2ffd',
    messagingSenderId: '291258072776',
    projectId: 'slushiesapp',
    authDomain: 'slushiesapp.firebaseapp.com',
    storageBucket: 'slushiesapp.firebasestorage.app',
    measurementId: 'G-2QZE98J8M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6uwbW2Y45kV236nILthzFmVGspJXkw_s',
    appId: '1:291258072776:android:f53090147f82d5993c2ffd',
    messagingSenderId: '291258072776',
    projectId: 'slushiesapp',
    storageBucket: 'slushiesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4cOrwY__DSzIdI2neMoBUaCXlmWKzag',
    appId: '1:291258072776:ios:80446090930fd2503c2ffd',
    messagingSenderId: '291258072776',
    projectId: 'slushiesapp',
    storageBucket: 'slushiesapp.firebasestorage.app',
    iosBundleId: 'com.example.slushies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4cOrwY__DSzIdI2neMoBUaCXlmWKzag',
    appId: '1:291258072776:ios:80446090930fd2503c2ffd',
    messagingSenderId: '291258072776',
    projectId: 'slushiesapp',
    storageBucket: 'slushiesapp.firebasestorage.app',
    iosBundleId: 'com.example.slushies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1VReTwxqNSHTz2JoirdcCuVDQJgFZY28',
    appId: '1:291258072776:web:fcdee26cd6abe5c23c2ffd',
    messagingSenderId: '291258072776',
    projectId: 'slushiesapp',
    authDomain: 'slushiesapp.firebaseapp.com',
    storageBucket: 'slushiesapp.firebasestorage.app',
    measurementId: 'G-43FDWJ7HPY',
  );
}
